import Image from "next/image";
import Navbar from '@/app/components/ui/Navbar';

export default function TermsOfConditions() {
    return (
        <>
            <Navbar initialBackground={true} />

            <section className="text-black bg-white p-6 pt-28 text-justify">

                <div className="bg-white p-10 mx-auto w-auto max-w-4xl">
                    <div className="flex justify-center mb-16">
                        <Image
                            src="/BTL-Logo-Horz-Dk-Gradient.svg"
                            alt="Website Logo"
                            width={500}
                            height={50}
                        />
                    </div>

                    <h1 className="text-2xl font-bold">Beat The Line LLC Terms of Service</h1>

                    <h2 className="text-xl font-semibold mt-4">1.	Acceptance of Terms</h2>
                    By accessing or using the Service, you signify that you have read, understood, and agree to be bound by this Terms of Service Agreement (“Agreement”) and to the collection and use of your information as set forth in the Beat The Line, LLC Privacy Policy (

                    ) , whether or not you are a registered or paid user of our Service.  This Agreement applies to all visitors, users, and others who access the Service (“Users”). Please read the entire agreement before using our Service. Beat The Line, LLC reserves the right to change, modify, add or remove portions of these Terms of Use, at any time. Please refer to {" "}
                    <a href="https://www.establishtherun.com/terms" className="text-blue-500 underline">https://www.establishtherun.com/terms</a>
                    {" "}to view the current Agreement.

                    <h2 className="text-xl font-semibold mt-4">2.	Service</h2>
                    You agree not to engage in any of the following prohibited activities: (i) copying, distributing, or sharing any part of the Service in any medium, including without limitation by any automated or non-automated “scraping”; (ii) using any automated system, including without limitation “robots,” “spiders,” “offline readers,” etc., to access the Service in a manner that sends more request messages to the Beat The Line, LLC servers than a human can reasonably produce in the same period of time by using a conventional web browser (iii) transmitting spam or other unsolicited email; (iv) attempting to interfere with, compromise the system integrity or security or decipher any transmissions to or from the servers running the Service; (v) taking any action that imposes, or may impose at our sole discretion an unreasonable or disproportionately large load on our infrastructure; (vi) uploading invalid data, viruses, worms, or other software agents through the Service; (vii) collecting or harvesting any personally identifiable information, including account names, from the Service; (viii) using the Service for any commercial solicitation purposes; (ix) impersonating another person or otherwise misrepresenting your affiliation with a person or entity, conducting fraud, hiding or attempting to hide your identity; (x) interfering with the proper working of the Service; (xi) accessing any content on the Service through any technology or means other than those provided or authorized by the Service; or (xii) bypassing the measures we may use to prevent or restrict access to the Service, including without limitation features that prevent or restrict use or copying of any content or enforce limitations on use of the Service or the content therein; (xiii) monetizing Beat The Line, LLC content through advertising, subscriptions or other means, or (xiv) sharing account log-in information so multiple persons are able to access the same paid account.
                    We may, without prior notice, change the Service; stop providing the Service or features of the Service, to you or to users generally; or create usage limits for the Service.  We may permanently or temporarily terminate or suspend your access to the Service without notice and liability for any reason, including if in our sole determination you violate any provision of this Agreement, or for no reason. We may also take legal action if your actions merit doing so. Upon termination for any reason or no reason, you continue to be bound by this Agreement.

                    <h2 className="text-xl font-semibold mt-4">3.	Proprietary Rights</h2>
                    The Service and all materials therein or transferred thereby, including, without limitation, software, images, text, graphics, illustrations, logos, patents, trademarks, service marks, copyrights and photographs (the “Beat The Line, LLC content”), and all Intellectual Property Rights related thereto, are the exclusive property of Beat The Line, LLC and its licensors.  Except as explicitly provided herein, nothing in this Agreement shall be deemed to create a license in or under any such Intellectual Property Rights, and you agree not to sell, license, rent, modify, distribute, copy, reproduce, transmit, publicly display, publicly perform, publish, adapt, edit or create derivative works from any Beat The Line, LLC content.  Use of the Beat The Line, LLC content for any purpose not expressly permitted by this Agreement is strictly prohibited.

                    <h2 className="text-xl font-semibold mt-4">4.	Description of Service</h2>
                    Beat The Line, LLC creates sports and gambling content that is provided for entertainment and educational purposes to its subscribers. Beat The Line, LLC reserves the right to create other unrelated content, sell related or unrelated items, or enter any other lawful line of business. Certain aspects of the Service may be provided for a fee or other charge. Some products will be one-time purchases and others may be subscriptions. If you elect to use paid aspects of the Service, you agree to the Pricing and Payment Terms as we may update them from time to time.  Beat The Line, LLC may add new services for additional fees and charges, or amend fees and charges for existing services, at any time in its sole discretion. Any change to our pricing or payment terms shall become effective in the billing cycle following notice of such change to you as provided in the Pricing and Payment Terms.
                    
                    <h2 className="text-xl font-semibold mt-4">5.	Privacy</h2>
                    
                    You understand that by using the Services you consent to the collection, use and disclosure of your personally identifiable information and aggregate data as set forth in our Privacy Policy (<a href="http://www.establishtherun.com/privacy" className="text-blue-500 underline">http://www.establishtherun.com/privacy</a>) , and to have your personally identifiable information collected, used, transferred to and processed in the United States.
                    <h2 className="text-xl font-semibold mt-4">6.	Security</h2>
                    When completing the Service’s registration process, you will disclose an email address and select a password. You are responsible for maintaining the confidentiality of the password and account, and are fully responsible for all activities that occur under your password or account. You agree to immediately notify Beat The Line of any unauthorized use of your password or account or any other breach of security, and to ensure that you exit from your account at the end of each session. Beat The Line cannot and will not be liable for any loss or damage arising from your failure to comply with this Section.
                    Beat The Line, LLC cares about the integrity and security of your personal information.  However, we cannot guarantee that unauthorized third parties will never be able to defeat our security measures or use your personal information for improper purposes.  You acknowledge that you provide your personal information at your own risk.
                    
                    <h2 className="text-xl font-semibold mt-4">7.	Third Party Links</h2>
                    The Service may contain links to third-party websites, services or other events or activities that are not owned or controlled by Beat The Line, LLC.  Beat The Line, LLC does not endorse or assume any responsibility for any such third-party sites, information, materials, products, or services.  If you access a third party website from the Service, you do so at your own risk, and you understand that this Agreement and Beat The Line, LLC’s Privacy Policy do not apply to your use of such sites.  You expressly relieve Beat The Line, LLC from any and all liability arising from your use of any third-party website, service, or content. Beat The Line, LLC, reserves the right to be paid by third parties for referrals made by clicking through or providing a promotional code. These third parties may include legal gambling web sites, or non-gambling web sites. Beat The Line, LLC is not responsible for any actions Users make on any third-party website it links or references. To be clear, Users are solely responsible for their own actions when visiting another web site linked or referenced on Beat The Line, LLC or by any of its owners, employees, or contractors.
                    
                    <h2 className="text-xl font-semibold mt-4">8.	Indemnity</h2>
                    You shall defend, indemnify, and hold harmless Beat The Line and the Beat The Line Associates  against any “Indemnified Claim,” meaning any third party claim, suit, or proceeding arising out of or related to Yours alleged or actual use of, misuse of, or failure to use the System, including without limitation: (a) claims related to unauthorized disclosure or exposure of personally identifiable information or other private information, including Customer Data; (b) claims related to infringement or violation of a copyright, trademark, trade secret, or privacy or confidentiality right by written material, images, logos or other content uploaded to the System through Your account, including without limitation by Customer Data; and (c) claims that use of the System through Your  account harasses, defames, or defrauds a third party or violates the CAN-Spam Act of 2003 or any other law or restriction on electronic advertising. Indemnified Claims include, without limitation, claims arising out of or related to Beat The Line’s negligence. Your obligations set forth in this Article 9 include retention and payment of attorneys and payment of court costs, as well as settlement at Your expense and payment of judgments. Beat The Line will have the right, not to be exercised unreasonably, to reject any settlement or compromise that requires that it admit wrongdoing or liability or subjects it to any ongoing affirmative obligations.
                    
                    <h2 className="text-xl font-semibold mt-4">9.	Representation and Warranties</h2>
                    You represent and warrants that: (a) You have the full right and authority to enter into, execute, and perform its obligations under this Agreement; (b) You have accurately identified Yourself and You have not provided any inaccurate information about Yourself to Beat The Line; and (c) You are a person aged 18 or older, a corporation, the sole proprietorship of an individual 18 years or older, or another entity authorized to do business pursuant to applicable law.
                    YOU ACCEPT THE SYSTEM “AS IS” AND AS AVAILABLE, WITH NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NONINFRINGEMENT OF INTELLECTUAL PROPERTY RIGHTS, OR ANY IMPLIED WARRANTY ARISING FROM STATUTE, COURSE OF DEALING, COURSE OF PERFORMANCE, OR USAGE OF TRADE. WITHOUT LIMITING THE GENERALITY OF THE FOREGOING: (a) BEAT THE LINE, LLC HAS NO OBLIGATION TO INDEMNIFY OR DEFEND YOU AGAINST CLAIMS RELATED TO INFRINGEMENT OF INTELLECTUAL PROPERTY; (b) BEAT THE LINE DOES NOT REPRESENT OR WARRANT THAT THE SYSTEM WILL PERFORM WITHOUT INTERRUPTION OR ERROR; AND (c) BEAT THE LINE DOES NOT REPRESENT OR WARRANT THAT THE SYSTEM IS SECURE FROM HACKING OR OTHER UNAUTHORIZED INTRUSION OR THAT CUSTOMER DATA WILL REMAIN PRIVATE OR SECURE.
                    BEAT THE LINE, LLC DOES NOT GUARANTEE THAT THE PRODUCTS WILL BE PROVIDED ERROR-FREE OR UNINTERRUPTED, OR THAT BEAT THE LINE WILL CORRECT ALL ERRORS. YOU ACKNOWLEDGE THAT BEAT THE LINE DOES NOT CONTROL THE TRANSFER OF DATA OVER COMMUNICATIONS FACILITIES, INCLUDING THE INTERNET, AND THAT THE SYSTEM MAY BE SUBJECT TO LIMITATIONS, DELAYS, AND OTHER PROBLEMS INHERENT IN THE USE OF SUCH COMMUNICATIONS FACILITIES. BEAT THE LINE IS NOT RESPONSIBLE FOR ANY DELAYS, DELIVERY FAILURES, OR OTHER DAMAGE RESULTING FROM SUCH PROBLEMS WHETHER OR NOT FORESEEABLE.
                    THERE IS NO GUARANTEE OR PROMISE THAT YOUR USE OF THE SYSTEM WILL ENABLE OR ASSIST YOU IN WINNING MONEY, OR THAT YOU WILL NOT LOSE MONEY, OR IMPROVE YOUR GAMBLING RESULTS. YOUR RESULTS WILL VARY AND WILL BE BASED ON YOUR ABILITIES, EXPERIENCE, KNOWLEDGE, CAPABILITIES, LEVEL OF DESIRE, AND AN INFINITE NUMBER OF VARIABLES BEYOND BEAT THE LINE, LLC’S CONTROL, INCLUDING VARIABLES BEAT THE LINE AND YOU HAVE NOT ANTICIPATED. EACH CUSTOMER’S RESULTS WILL VARY.
                    TO THE EXTENT NOT PROHIBITED BY LAW, THESE WARRANTIES ARE EXCLUSIVE AND THERE ARE NO OTHER EXPRESS OR IMPLIED WARRANTIES OR CONDITIONS.
                    
                    <h2 className="text-xl font-semibold mt-4">10.	Limitation of Liability</h2>
                    TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL COMPANY, ITS AFFILIATES, AGENTS, DIRECTORS, EMPLOYEES, SUPPLIERS OR LICENSORS BE LIABLE FOR ANY DIRECT, INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING WITHOUT LIMITATION DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES, ARISING OUT OF OR RELATING TO THE USE OF, OR INABILITY TO USE, THIS SERVICE.  UNDER NO CIRCUMSTANCES WILL COMPANY BE RESPONSIBLE FOR ANY DAMAGE, LOSS OR INJURY RESULTING FROM HACKING, TAMPERING OR OTHER UNAUTHORIZED ACCESS OR USE OF THE SERVICE OR YOUR ACCOUNT OR THE INFORMATION CONTAINED THEREIN.
                    TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, COMPANY ASSUMES NO LIABILITY OR RESPONSIBILITY FOR ANY (I) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT; (II) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO OR USE OF OUR SERVICE; (III) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION STORED THEREIN; (IV) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE SERVICE; (V) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE THAT MAY BE TRANSMITTED TO OR THROUGH OUR SERVICE BY ANY THIRD PARTY; (VI) ANY ERRORS OR OMISSIONS IN ANY CONTENT OR FOR ANY LOSS OR DAMAGE INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE THROUGH THE SERVICE; AND/OR (VII) THE DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY THIRD PARTY.  IN NO EVENT SHALL COMPANY, ITS AFFILIATES, AGENTS, DIRECTORS, EMPLOYEES, SUPPLIERS, OR LICENSORS BE LIABLE TO YOU FOR ANY CLAIMS, PROCEEDINGS, LIABILITIES, OBLIGATIONS, DAMAGES, LOSSES OR COSTS IN AN AMOUNT EXCEEDING THE AMOUNT YOU PAID TO COMPANY HEREUNDER OR $100.00, WHICHEVER IS GREATER.
                    THIS LIMITATION OF LIABILITY SECTION APPLIES WHETHER THE ALLEGED LIABILITY IS BASED ON CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY, OR ANY OTHER BASIS, EVEN IF COMPANY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.  THE FOREGOING LIMITATION OF LIABILITY SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW IN THE APPLICABLE JURISDICTION.
                    SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATIONS OR EXCLUSIONS MAY NOT APPLY TO YOU.  THIS AGREEMENT GIVES YOU SPECIFIC LEGAL RIGHTS, AND YOU MAY ALSO HAVE OTHER RIGHTS WHICH VARY FROM STATE TO STATE.  THE EXCLUSIONS AND LIMITATIONS OF LIABILITY UNDER THIS AGREEMENT WILL NOT APPLY TO THE EXTENT PROHIBITED BY APPLICABLE LAW.
                    The Service is controlled and operated from facilities in the United States.  Beat The Line, LLC makes no representations that the Service is appropriate or available for use in other locations.  Those who access or use the Service from other jurisdictions do so at their own volition and are entirely responsible for compliance with all applicable United States and local laws and regulations, including but not limited to export and import regulations.  You may not use the Service if you are a resident of a country embargoed by the United States, or are a foreign person or entity blocked or denied by the United States government.  Unless otherwise explicitly stated, all materials found on the Service are solely directed to individuals, companies, or other entities located in the United States.
                    
                    <h1 className="text-2xl font-bold mt-4">11.	Miscellaneous</h1>

                    <h2 className="text-xl font-semibold mt-4">11.1. Independent Contractors.</h2>The parties are independent contractors and will so represent themselves in all regards. Neither party is the agent of the other, and neither may make commitments on the other’s behalf.
                    <h2 className="text-xl font-semibold mt-4">11.2. Notices.</h2>Beat The Line may send notices pursuant to this Agreement to You at the email contact points provided by You, and such notices will be deemed received twenty four (24) hours after they are sent. You may send notices pursuant to this Agreement to Beat The Line at support@establishtherun.com , and such notices will be deemed received twenty four (24) hours after they are sent.
                    <h2 className="text-xl font-semibold mt-4">11.3. Force Majeure.</h2>No delay, failure, or default, other than a failure to pay fees when due, will constitute a breach of this Agreement to the extent caused by acts of war, terrorism, hurricanes, earthquakes, other acts of God or of nature, strikes or other labor disputes, riots or other acts of civil disorder, embargoes, or other causes beyond the performing party’s reasonable control.
                    <h2 className="text-xl font-semibold mt-4">11.4. Assignment & Successors.</h2>You may not assign this Agreement or any of its rights or obligations hereunder without Beat The Line, LLC’s express written consent. Except to the extent forbidden in this Section 11.4, this Agreement will be binding upon and inure to the benefit of the parties’ respective successors and assigns.
                    <h2 className="text-xl font-semibold mt-4">11.5. Severability.</h2>To the extent permitted by applicable law, the parties hereby waive any provision of law that would render any clause of this Agreement invalid or otherwise unenforceable in any respect. In the event that a provision of this Agreement is held to be invalid or otherwise unenforceable, such provision will be interpreted to fulfill its intended purpose to the maximum extent permitted by applicable law, and the remaining provisions of this Agreement will continue in full force and effect.
                    <h2 className="text-xl font-semibold mt-4">11.6. No Waiver.</h2>Neither party will be deemed to have waived any of its rights under this Agreement by lapse of time or by any statement or representation other than by an authorized representative in an explicit written waiver. No waiver of a breach of this Agreement will constitute a waiver of any other breach of this Agreement.
                    <h2 className="text-xl font-semibold mt-4">11.7. Choice of Law & Jurisdiction:</h2> This Agreement will be governed solely by the internal laws of the State of Arizona, United States of America, without reference to: (a) any conflicts of law principle that would apply the substantive laws of another jurisdiction to the parties’ rights or duties; (b) the 1980 United Nations Convention on Contracts for the International Sale of Goods; or (c) other international laws. The parties consent to the personal and exclusive jurisdiction of the federal and state courts of Maricopa County, Arizona.
                    <h2 className="text-xl font-semibold mt-4">11.8. Conflicts.</h2>In the event of any conflict between this Agreement and any Beat The Line, LLC policy posted online, including without limitation the AUP or Privacy Policy, the terms of this Agreement will govern.
                    <h2 className="text-xl font-semibold mt-4">11.9. Construction.</h2>The parties agree that the terms of this Agreement result from negotiations between them. This Agreement will not be construed in favor of or against either party by reason of authorship.
                    <h2 className="text-xl font-semibold mt-4">11.10. Technology Export.</h2>You shall not: (a) permit any third party to access or use the System in violation of any U.S. law or regulation; or (b) export any software provided by Beat The Line or otherwise remove it from the United States except in compliance with all applicable U.S. laws and regulations. Without limiting the generality of the foregoing, You shall not permit any third party to access or use the System in, or export such software to, a country subject to a United States embargo (including, as of the Effective Date, Iran, North Korea, Sudan, and Syria). You agree that no data, information, software programs and/or materials resulting from Your use of the System (or direct product thereof) will be exported, directly or indirectly, in violation of these laws. You may visit the U.S. Department of Treasury website located at <a href="http://www.treasury.gov/resource-center/sanctions/Programs/Pages/Programs.aspx" className="text-blue-500 underline">http://www.treasury.gov/resource-center/sanctions/Programs/Pages/Programs.aspx</a> for more information.
                    <h2 className="text-xl font-semibold mt-4">11.11. Entire Agreement.</h2>This Agreement sets forth the entire agreement of the parties and supersedes all prior or contemporaneous writings, negotiations, and discussions with respect to its subject matter. Neither party has relied upon any such prior or contemporaneous communications.
                    <h2 className="text-xl font-semibold mt-4">11.12. Amendment.</h2>Beat The Line may amend this Agreement from time to time by posting an amended version on the website at which access to the System may be ordered. As a condition of this Agreement, you agree to periodically check the posted version of this Agreement. You agree that your continued use of the System after the date this Agreement has been amended will constitute your consent and acceptance of the Agreement as amended. This Agreement may not be amended in any other way except through a written agreement by authorized representatives of each party. Notwithstanding the foregoing provisions of this Section 11.12, Beat The Line, LLC may revise its privacy policies and AUP at any time by posting a new version of either at Beat The Line, LLC’s websites, and such new version will become effective on the date it is posted.
                </div>
            </section>
        </>
    );
}
